#!/bin/bash

if [ -z "$1" ]
  then
    read -rp $'Exhentai gallery link:' url
  else
    url="$1"
fi
if [ -z "$url" ]
  then
    echo "Please provide a link"
    echo "or --help for help"
    exit
fi 
if [ "$url" == "--help" ]
  then
    echo "ExHentai Downloader for Linux"
    echo " "
    echo "Usage:"
    echo "  exh-downloader gallery_url"
    echo "  example: exh-downloader http://exhentai.org/g/918667/f611a5c353/"
    echo "  exh-downloader --help for this help"
    exit
fi
realurl="`echo $url | grep 'http://exhentai.org'`"
if [ -z "$url" ]
  then
    echo "Please provide a link"
    exit
fi
if [ -z "$realurl" ]
  then
    echo "Please provide a valid exhentai link with http"
    echo "example: http://exhentai.org/g/918667/f611a5c353/"
    exit
fi
echo "Starting ExHentai Downloader Linux"
sleep 1
echo "Downloading from $url"
sleep 1
echo "Fetching metadata..."
page="`wget -c -q --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$url" -O- | hxselect -i "td.gdt2" | lynx -stdin -dump | grep -o -P '.{0,4}pages' | sed 's| ||;s|pages||'`"
if [[ $page -lt 1 ]]
  then 
    echo "ERROR gallery not found"
    echo "Are you sure the link was correct?"
    exit
fi
pagegall="`expr $page / 40`"
wget -c -q --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$url" -O- | hxselect -i "title" | sed 's|<title>||;s| - ExHentai.org</title>||' > $HOME/.xhdownloader/exhentai.title
extitle="`cat $HOME/.xhdownloader/exhentai.title`"
mkdir "$extitle"
cd "$extitle"
echo "Title: $extitle"
echo "length: $page"

if [ $pagegall -ge 1 ]
	then
		echo "Downloading Multiple page gallery"
		sleep 5
		gallnum=0
		while [[ $gallnum -le $pagegall ]]; do
			wget -c --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$url"?p=$gallnum -O- | hxselect -i  "div.gdtm a" | lynx -stdin -dump > $HOME/.xhdownloader/xh.scrap
			cat $HOME/.xhdownloader/xh.scrap | grep -o -P 'http://exhentai.org/.{0,27}' > $HOME/.xhdownloader/xh.gall
			while read line; do
				wget -c -q --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$line" -O- | hxnormalize | egrep "src.*jpg|src.*png" | grep -v "exhentai" | sed 's|src="||;s|.$||' | wget -c --load-cookies=$HOME/.xhdownloader/exhentai.cookie -i-
			done < $HOME/.xhdownloader/xh.gall
			let gallnum=$gallnum+1
		done	
	else
		echo "Downloading single page gallery"
		sleep 5
		wget -c --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$url" -O- | hxselect -i  "div.gdtm a" | lynx -stdin -dump > $HOME/.xhdownloader/xh.scrap
		cat $HOME/.xhdownloader/xh.scrap | grep -o -P 'http://exhentai.org/.{0,27}' > $HOME/.xhdownloader/xh.gall
		while read line; do
			wget -c -q --load-cookies=$HOME/.xhdownloader/exhentai.cookie "$line" -O- | hxnormalize | egrep "src.*jpg|src.*png" | grep -v "exhentai" | sed 's|src="||;s|.$||' | wget -c --load-cookies=$HOME/.xhdownloader/exhentai.cookie -i-
		done < $HOME/.xhdownloader/xh.gall
fi
rm $HOME/.xhdownloader/xh.scrap
rm $HOME/.xhdownloader/xh.gall
rm $HOME/.xhdownloader/exhentai.title
cd ../
